# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-operator-leader-election-rolebinding
  namespace:  "{{ .AuthRealm.Namespace }}-{{ .AuthRealm.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex-operator-leader-election-role
  namespace: "{{ .AuthRealm.Name }}"
subjects:
- kind: ServiceAccount
  name: dex-operator-manager
  namespace: "{{ .AuthRealm.Namespace }}-{{ .AuthRealm.Name }}"
