# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-operator-leader-election-rolebinding
  namespace:  "idp-mgmt-dex"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex-operator-leader-election-role
  namespace: "dex-mgmt-dex"
subjects:
- kind: ServiceAccount
  name: dex-operator-manager
  namespace: "idp-mgmt-dex"
