# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: dex-operator-manager
  namespace: system
