# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-operator-manager-role
subjects:
- kind: ServiceAccount
  name: dex-operator-manager
  namespace: "{{ .AuthRealm.Name }}"
