
apiVersion: v1
kind: Service
metadata:
  name: idp-mgmt-webhook-service
  namespace: {{ .Namespace }}
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": idp-mgmt-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 6443
  selector:
    control-plane: idp-mgmt-webhook-service
