# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idp-mgmt-webhook-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idp-mgmt-webhook-service
subjects:
  - kind: ServiceAccount
    name: idp-mgmt-webhook-service
    namespace: idp-mgmt-config
 