ARG DOCKER_BASE_IMAGE

FROM $DOCKER_BASE_IMAGE

ARG REMOTE_SOURCE
ARG REMOTE_SOURCE_DIR
ARG GITHUB_TOKEN

ENV OPERATOR=/usr/local/bin/manager \
    USER_UID=1001 \
    USER_NAME=idp-mgmt-operator
   
USER root
# Install unzip
RUN microdnf update
RUN microdnf install -y --nodocs jq
RUN microdnf install -y --nodocs openssl

# Copy needed crd for test
COPY test/config/crd/external test/config/crd/external

# install operator binary
RUN cp ${OPERATOR}-coverage ${OPERATOR}

USER ${USER_UID}

ENTRYPOINT ["/usr/local/bin/entrypoint-coverage"]

