resources:
- webhook-apiservice.yaml
- webhook-clusterrole.yaml
- service_account.yaml
- webhook-clusterrolebinding.yaml
- webhook-service.yaml
- webhook.yaml
- webhook-validating-config.yaml

# configurations:
# - kustomizeconfig.yaml
