
apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: idp-mgmt-config
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": cluster-manager-registration-webhook
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
