apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.admission.identityconfig.identitatem.io
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
spec:
  group: admission.identityconfig.identitatem.io
  version: v1alpha1
  service:
    name: kubernetes
    namespace: default
  groupPriorityMinimum: 10000
  versionPriority: 20
