
apiVersion: v1
kind: Service
metadata:
  name: idp-mgmt-webhook
  namespace: idp-mgmt-config
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": idp-mgmt-webhook
spec:
  ports:
    - port: 443
      targetPort: 6443
  selector:
    control-plane: webhook
