apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: idp-mgmt-operator-leader-election-rolebinding
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: idp-mgmt-operator-manager
  namespace: idp-mgmt-config
