# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idp-strategy-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idp-strategy-operator-role
subjects:
- kind: ServiceAccount
  name: idp-strategy-operator-manager
  namespace: {{ .Namespace }}
