# permissions for end users to view authrealms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authrealm-viewer-role
rules:
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrealms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrealms/status
  verbs:
  - get
