# permissions for end users to edit authrealms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authrealm-editor-role
rules:
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrealms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrealms/status
  verbs:
  - get
