
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - identitatem.io
  resources:
  - authrealms
  - identityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identitatem.io
  resources:
  - authrealms/status
  - identityproviders/status
  verbs:
  - get
  - patch
  - update
