
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrhelms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identitatem.io.my.domain
  resources:
  - authrhelms/status
  verbs:
  - get
  - patch
  - update
