apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identitatem.io:clusteroauth-admin-aggregated-clusterrole
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["oauth"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]