apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - args:
        - installer
        env:
        - name: RELATED_IMAGE_DEX_OPERATOR
          value: "quay.io/identitatem/dex-operator:latest"
        - name: RELATED_IMAGE_DEX_SERVER
          value: quay.io/dexidp/dex:v2.28.1
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        name: installer
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /tmp/coverage-installer
            name: coverage-dir  
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: idp-mgmt-installer-controller-manager
      terminationGracePeriodSeconds: 30
      volumes:
        - name: coverage-dir
          hostPath:
            # directory location on host
            path: /tmp/coverage-installer
            # this field is optional
            type: Directory
