apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        idp-antiaffinity-selector: idp-mgmt-installer-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: idp-antiaffinity-selector
                      operator: In
                      values:
                        - idp-mgmt-installer-controller
                topologyKey: topology.kubernetes.io/zone
              weight: 70
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: idp-antiaffinity-selector
                      operator: In
                      values:
                        - idp-mgmt-installer-controller
                topologyKey: kubernetes.io/hostname
              weight: 35
      containers:
      - args:
        - installer
        env:
        - name: RELATED_IMAGE_DEX_OPERATOR
          value: "quay.io/identitatem/dex-operator:0.1-f82645dbefa2e0a634186e662adf139cff60523b"
        - name: RELATED_IMAGE_DEX_SERVER
          value: ghcr.io/dexidp/dex:v2.30.2
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        name: installer
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 150Mi
      serviceAccountName: idp-mgmt-installer-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
        - key: dedicated
          operator: Exists
          effect: NoSchedule
