// Copyright Contributors to the Open Cluster Management project

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuthRealmListerExpansion allows custom methods to be added to
// AuthRealmLister.
type AuthRealmListerExpansion interface{}

// AuthRealmNamespaceListerExpansion allows custom methods to be added to
// AuthRealmNamespaceLister.
type AuthRealmNamespaceListerExpansion interface{}
