// Copyright Contributors to the Open Cluster Management project

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/identitatem/idp-mgmt-operator/api/client/clientset/versioned/typed/authrealm/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIdentitatemV1 struct {
	*testing.Fake
}

func (c *FakeIdentitatemV1) AuthRealms(namespace string) v1.AuthRealmInterface {
	return &FakeAuthRealms{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIdentitatemV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
