// Copyright Contributors to the Open Cluster Management project

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/identitatem/idp-mgmt-operator/api/client/clientset/versioned"
	internalinterfaces "github.com/identitatem/idp-mgmt-operator/api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/identitatem/idp-mgmt-operator/api/client/listers/identitatem/v1alpha1"
	identitatemv1alpha1 "github.com/identitatem/idp-mgmt-operator/api/identitatem/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IdentityProviderInformer provides access to a shared informer and lister for
// IdentityProviders.
type IdentityProviderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IdentityProviderLister
}

type identityProviderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIdentityProviderInformer constructs a new informer for IdentityProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIdentityProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIdentityProviderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIdentityProviderInformer constructs a new informer for IdentityProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIdentityProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IdentitatemV1alpha1().IdentityProviders(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IdentitatemV1alpha1().IdentityProviders(namespace).Watch(context.TODO(), options)
			},
		},
		&identitatemv1alpha1.IdentityProvider{},
		resyncPeriod,
		indexers,
	)
}

func (f *identityProviderInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIdentityProviderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *identityProviderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&identitatemv1alpha1.IdentityProvider{}, f.defaultInformer)
}

func (f *identityProviderInformer) Lister() v1alpha1.IdentityProviderLister {
	return v1alpha1.NewIdentityProviderLister(f.Informer().GetIndexer())
}
