// Copyright Contributors to the Open Cluster Management project

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/identitatem/idp-mgmt-operator/api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AuthRealms returns a AuthRealmInformer.
	AuthRealms() AuthRealmInformer
	// IdentityProviders returns a IdentityProviderInformer.
	IdentityProviders() IdentityProviderInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AuthRealms returns a AuthRealmInformer.
func (v *version) AuthRealms() AuthRealmInformer {
	return &authRealmInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IdentityProviders returns a IdentityProviderInformer.
func (v *version) IdentityProviders() IdentityProviderInformer {
	return &identityProviderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
