// Copyright Contributors to the Open Cluster Management project

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/identitatem/idp-mgmt-operator/api/identitatem/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIdentityProviders implements IdentityProviderInterface
type FakeIdentityProviders struct {
	Fake *FakeIdentitatemV1alpha1
	ns   string
}

var identityprovidersResource = schema.GroupVersionResource{Group: "identitatem.io", Version: "v1alpha1", Resource: "identityproviders"}

var identityprovidersKind = schema.GroupVersionKind{Group: "identitatem.io", Version: "v1alpha1", Kind: "IdentityProvider"}

// Get takes name of the identityProvider, and returns the corresponding identityProvider object, and an error if there is any.
func (c *FakeIdentityProviders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(identityprovidersResource, c.ns, name), &v1alpha1.IdentityProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityProvider), err
}

// List takes label and field selectors, and returns the list of IdentityProviders that match those selectors.
func (c *FakeIdentityProviders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IdentityProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(identityprovidersResource, identityprovidersKind, c.ns, opts), &v1alpha1.IdentityProviderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IdentityProviderList{ListMeta: obj.(*v1alpha1.IdentityProviderList).ListMeta}
	for _, item := range obj.(*v1alpha1.IdentityProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested identityProviders.
func (c *FakeIdentityProviders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(identityprovidersResource, c.ns, opts))

}

// Create takes the representation of a identityProvider and creates it.  Returns the server's representation of the identityProvider, and an error, if there is any.
func (c *FakeIdentityProviders) Create(ctx context.Context, identityProvider *v1alpha1.IdentityProvider, opts v1.CreateOptions) (result *v1alpha1.IdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(identityprovidersResource, c.ns, identityProvider), &v1alpha1.IdentityProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityProvider), err
}

// Update takes the representation of a identityProvider and updates it. Returns the server's representation of the identityProvider, and an error, if there is any.
func (c *FakeIdentityProviders) Update(ctx context.Context, identityProvider *v1alpha1.IdentityProvider, opts v1.UpdateOptions) (result *v1alpha1.IdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(identityprovidersResource, c.ns, identityProvider), &v1alpha1.IdentityProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityProvider), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIdentityProviders) UpdateStatus(ctx context.Context, identityProvider *v1alpha1.IdentityProvider, opts v1.UpdateOptions) (*v1alpha1.IdentityProvider, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(identityprovidersResource, "status", c.ns, identityProvider), &v1alpha1.IdentityProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityProvider), err
}

// Delete takes name of the identityProvider and deletes it. Returns an error if one occurs.
func (c *FakeIdentityProviders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(identityprovidersResource, c.ns, name), &v1alpha1.IdentityProvider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIdentityProviders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(identityprovidersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IdentityProviderList{})
	return err
}

// Patch applies the patch and returns the patched identityProvider.
func (c *FakeIdentityProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(identityprovidersResource, c.ns, name, pt, data, subresources...), &v1alpha1.IdentityProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityProvider), err
}
