// Copyright Contributors to the Open Cluster Management project

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/identitatem/idp-mgmt-operator/api/client/clientset/versioned/typed/identitatem/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIdentitatemV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIdentitatemV1alpha1) AuthRealms(namespace string) v1alpha1.AuthRealmInterface {
	return &FakeAuthRealms{c, namespace}
}

func (c *FakeIdentitatemV1alpha1) IdentityProviders(namespace string) v1alpha1.IdentityProviderInterface {
	return &FakeIdentityProviders{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIdentitatemV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
