# Copyright Red Hat

name: Publish

on:
  push:
    branches: [ main, release-* ]

jobs:
  publish:
    if: github.repository_owner == 'identitatem'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Dependencies and Publish
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export VERSION="0.1.1-$(date -u +'%Y%m%d-%H-%M-%S')"
        make publish
