# Copyright Red Hat

on:
  push:
    # Sequence of patterns matched against refs/tags
    # Has to use not-quite-regex from https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install kubebuilder
      run: make envtest-tools

    - name: Publish a release tagged image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export VERSION=${GITHUB_REF##*/}
        export IMG=quay.io/identitatem/idp-mgmt-operator:${GITHUB_REF##*/}
        export PREV_BUNDLE_INDEX_IMG=quay.io/identitatem/idp-mgmt-operator-catalog:v0.3.0
        export KUBEBUILDER_ASSETS=$HOME/kubebuilder/bin;
        make publish
